version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - export BUCKET=s3-cloud-pipeline-artifacts
      - aws cloudformation package --template-file serverless.yml --s3-bucket githubbucket1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - serverless.yml
    - outputtemplate.yml
