service: GitHubActions
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1 
  
Function:
  HelloWorldFunction-GitHub:
      Handler: handler/aws.lambda_handler
      Runtime: python3.7
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /Hello
            Method: get
#functions:
 # function2:
  #  handler: handler/aws.lambda_handler
   # runtime: python3.7
    #timeout: 300
    #memorySize: 256
    #package:
     # include:
      #  - Lambda_function2.py
    #policies:
     # - AmazonS3FullAccess
     # - AmazonTextractFullAccess
     # - CloudWatchLogsFullAccess
     # - AWSLambdaBasicExecutionRole
     # - AmazonDynamoDBFullAccess
    # events:
      # - http:
        #  path: /customer
         # method: post 
