service: GitHubActions

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1
      
functions:
  function1:
      handler: ./HttpFunction1/AWSFunction.aws
      runtime: python3.7
      timeout: 300
      memorySize: 256
      autoPublishAlias: DEV
      policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      events:
        - restApi:
            path: /Hello
            method: get
