AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create an API gateway with triggered Lambda function
Resources:
  ApiResource:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      FunctionName: HelloWorldFunction-GitHub
      Handler: Lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      AutoPublishAlias: DEV
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /Hello
            Method: get
            RestApiId: !Ref ApiResource
            
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      FunctionName: PostFunction-GitHub
      Handler: Lambda_function2.lambda_handler2
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      AutoPublishAlias: DEV
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /customer
            Method: post
            RestApiId: !Ref ApiResource   
