service: GitHubActions

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  endpointType: REGIONAL
  package:
    exclude:
     - .git*/**
     - .vscode/**
     - AZURE_Functions/**
     - host.json
     - proxies.json
     - .gitignore
     - .funcignore

functions:
  hello:
    handler: AWS_Functions/AWS.lambda_handler
    runtime: python3.8
    timeout: 300
    memorySize: 256
    autoPublishAlias: DEV
    policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
    events:
     - http:
        path: /Hello
        method: get
