service: GitHubActions

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1
      
functions:
  function1:
    handler: Lambda_function../handler/aws.py
    runtime: python3.7
    timeout: 300
    memorySize: 256
    policies:
      - AmazonS3FullAccess
      - AmazonTextractFullAccess
      - CloudWatchLogsFullAccess
      - AWSLambdaBasicExecutionRole
    events:
     - http:
          path: /Hello
          method: get

function:
  function2:
    handler: Lambda_function2../handler/aws.py
    runtime: python3.7
    timeout: 300
    memorySize: 256
    policies:
      - AmazonS3FullAccess
      - AmazonTextractFullAccess
      - CloudWatchLogsFullAccess
      - AWSLambdaBasicExecutionRole
      - AmazonDynamoDBFullAccess
    events:
     - http:
          path: /customer
          method: post 
