service: GitHubActions

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1
      
Functions:
  function1:
      Handler: Lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 300
      MemorySize: 256
      AutoPublishAlias: DEV
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /Hello
            Method: get
            
  Function2:
      Handler: Lambda_function2.lambda_handler2
      Runtime: python3.7
      Timeout: 300
      MemorySize: 256
      AutoPublishAlias: DEV
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /customer
            Method: post
