service: GitHubActions
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1  
functions:
  function1:
    handler: handler/aws.lambda_handler
    runtime: python3.7
    timeout: 300
    memorySize: 256
    package:
      include:
        - Lambda_function.py
    policies:
      - AmazonS3FullAccess
      - AmazonTextractFullAccess
      - CloudWatchLogsFullAccess
      - AWSLambdaBasicExecutionRole
    events:
      - http:
          path: /Hello
          method: get
functions:
  function2:
    handler: handler/aws.lambda_handler
    runtime: python3.7
    timeout: 300
    memorySize: 256
    package:
      include:
        - Lambda_function2.py
    policies:
      - AmazonS3FullAccess
      - AmazonTextractFullAccess
      - CloudWatchLogsFullAccess
      - AWSLambdaBasicExecutionRole
      - AmazonDynamoDBFullAccess
    events:
      - http:
          path: /customer
          method: post 
