name: AzureARMtemplateDeploy and AWS Github Python app
env:
  AZURE_FUNCTIONAPP_NAME: funcapp-jj4fl7pkmhioq
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.8'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.8]
      steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}, ${{ matrix.python-version }}
          
      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
          pip install --pre azure-cosmos
          npm install @azure/cosmos
          npm i serverless-azure-functions
          npm i serverless --save-dev
          
      - name: Deploy Azure Resource Manager (ARM) Template
        id: DeployARM
        uses: whiteducksoftware/azure-arm-action@v3.2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          deploymentName: GitHubActions-Deploy
          resourceGroupName: GitHubARM
          templateLocation: ./azuredeploy.json
    
      - name: Serverless
        uses: serverless/github-action@master
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.1.8
        id: Deploy_function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile:  ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      
 
    #credentials to connect to AWS
      - name: Configure AWS credentials from Admin account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          profile_name: default
          runtime: python3.8
    
    # Runs a set of commands using the runners shell; THIS DOESN'T WORK
      - name: Run multiple commands for install environment
        run: |
           #install PIP
           python -m pip install pip --upgrade pip
           #install all dependencies as defined by requirements.txt in the current directory
           pip3 install -r requirements.txt
           npm install
           #ensuring current working directory is accessible by the function--this might not be doing anything
           export PATH=$PATH:$(pwd)

      #Deploy main.py to AWS
      - name: Serverless
        uses: serverless/github-action@master
        with:
          args: deploy --region eu-central-1
